# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Marcin Biegun'
tagline:          'splitting reality'
description:      'Scalable Ruby, full-stack, self-management, visual arts'
url:              http://marcinbiegun.com
baseurl:          /

author:
  name:           'Marcin Biegun'
  url:            https://marcinbiegun.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

social:
  twitter: kotutku
  github: marcinbiegun
  linkedin: mabiegun
