# Site settings
title: 'n23.pl'
description: 'Marcin Biegun'
url: 'http://n23.pl'
baseurl: '/'
google_analytics: 'UA-85551651-1'
show_rss_link: false

author:
  name: 'Marcin Biegun'
  email: 'maxrcxin!xmxm.xsxt'
  github_username: marcinbiegun
  instagram_username: spacecatlabs
  twitter_username: nagl23_
  youtube_channel_id: 'UCF-75X6bzZz0l0AWsdgYyVA'
  # pinterest_username: nagl23_
  # linkedin_username: mabiegun

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
